In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline 
pd.set_option('display.max_columns',None)

# Training without mixing columns

In [8]:
train_df=pd.read_csv('Training_Missing_removed.csv',index_col='application_key')
colm= [ i for i in range(48)]
train_df.columns=colm
med_colm=[0,1,2,3,4,8,9,18,19,27,28,32,33,35,36,37,38,41,42,43]
zero_replace_colm=[5,6,7,10,11,12,14,15,16,17,20,21,22,23,24,25,26,
                  29,30,31,34,39,40,44,45]
train_df[med_colm]=train_df[med_colm].replace(np.NaN,train_df[med_colm].median())
train_df[zero_replace_colm]=train_df[zero_replace_colm].replace(np.NaN,0)
train_df.head()
# train_df.to_csv('Training_3oct_sh.csv')

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47
application_key,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
230032,1696.0,1.6541,0.000,0.0,0.0,0.0,6015.0,322.0,40369.0,18414.0,0.0,6423.0,3067.0,123875.0,0.0,1.0,1.0,1.0,3.0,3.0,94.78,8987.18,0.00,72.25,1462.0,4532.0,2890.0,61.0,4532.0,1095.0,3376.0,625.0,1.1667,1.0,0.0,8.0,10.0,4.0,1.0,73.780,82.547,0.08696,10.0,0.63899,0.0,0.0,0.0,0.0
230033,1846.0,0.8095,0.000,0.0,0.0,102.0,7532.0,3171.0,18234.0,13664.0,0.0,765.0,1931.0,42613.0,0.0,0.0,0.0,0.0,0.0,0.0,74.25,953.06,953.06,4.80,1028.0,2099.0,2099.0,30386.0,2281.0,0.0,2251.0,169.0,0.4167,0.0,0.0,8.0,0.0,2.0,0.0,99.129,0.000,0.00000,13.0,0.63836,0.0,0.0,1.0,1.0
230034,1745.0,0.4001,0.000,0.0,0.0,0.0,2536.0,0.0,14171.0,2536.0,0.0,0.0,0.0,76109.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.0,0.0,0.0,669.0,4623.0,3772.0,0.0,0.0,25.0833,0.0,0.0,1.0,3.0,1.0,0.0,0.000,29.290,0.00000,1.0,1.00000,0.0,0.0,0.0,1.0
230035,1739.0,0.2193,0.000,0.0,0.0,1982.0,26440.0,4955.0,20316.0,37013.0,0.0,0.0,0.0,84235.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,1308.0,2525.0,791.0,91.0,5992.0,0.0,3741.0,215.0,10.3333,0.0,0.0,3.0,3.0,2.0,0.0,96.272,0.000,0.15385,3.0,0.53241,0.0,0.0,1.0,0.0
230036,1787.0,0.0118,0.225,0.0,0.0,5451.0,5494.0,5494.0,7987.0,4696.0,0.0,2257.0,27815.0,123875.0,524848.0,0.0,0.0,0.0,0.0,0.0,20.51,796.67,0.00,28.72,801.0,2281.0,2281.0,487.0,2707.0,0.0,1947.0,158.0,0.9167,0.0,0.0,2.0,3.0,2.0,0.0,115.019,0.000,0.00000,1.0,0.92665,0.0,0.0,1.0,0.0

# lead board and evalution clean without merging

In [9]:
train_df=pd.read_csv('Leaderboard_Missing_removed.csv',index_col='application_key')
colm= [ i for i in range(47)]
train_df.columns=colm
med_colm=[0,1,2,3,4,8,9,18,19,27,28,32,33,35,36,37,38,41,42,43]
zero_replace_colm=[5,6,7,10,11,12,14,15,16,17,20,21,22,23,24,25,26,
                  29,30,31,34,39,40,44,45]
train_df[med_colm]=train_df[med_colm].replace(np.NaN,train_df[med_colm].median())
train_df[zero_replace_colm]=train_df[zero_replace_colm].replace(np.NaN,0)
train_df.to_csv('Lead_3oct_sh.csv')

train_df=pd.read_csv('Evalution_missing_removed.csv',index_col='application_key')
colm= [ i for i in range(47)]
train_df.columns=colm
med_colm=[0,1,2,3,4,8,9,18,19,27,28,32,33,35,36,37,38,41,42,43]
zero_replace_colm=[5,6,7,10,11,12,14,15,16,17,20,21,22,23,24,25,26,
                  29,30,31,34,39,40,44,45]
train_df[med_colm]=train_df[med_colm].replace(np.NaN,train_df[med_colm].median())
train_df[zero_replace_colm]=train_df[zero_replace_colm].replace(np.NaN,0)
train_df.to_csv('Evalution_3oct_sh.csv')

In [10]:
train_df.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46
application_key,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
570075,1860.0,0.4668,0.212,0.0,0.0,1621.0,151211.0,22298.0,161588.0,207987.0,0.0,3625.0,0.0,72343.0,1189200.0,0.0,0.0,0.0,0.0,0.0,68.909,0.0,0.0,0.07,1380.0,6844.0,6844.0,639.0,7118.0,0.0,0.0,1134.0,2.5833,0.0,0.0,2.0,6.0,0.0,0.0,0.000,0.000,0.00000,10.0,0.95597,0.0,0.0,0.0
570076,1797.0,0.4451,0.000,0.0,0.0,920.0,8124.0,920.0,30429.0,14070.0,0.0,11991.0,5627.0,58469.0,148650.0,0.0,0.0,0.0,1.0,1.0,66.469,6288.0,0.0,66.85,2734.0,4228.0,4228.0,1886.0,11102.0,4745.0,0.0,719.0,30.6667,0.0,0.0,4.0,6.0,1.0,0.0,0.000,14.888,0.00000,4.0,0.45250,0.0,0.0,0.0
570077,1826.0,0.0423,0.000,0.0,0.0,3478.0,7209.0,3964.0,16054.0,24924.0,0.0,486.0,0.0,56487.0,0.0,0.0,0.0,0.0,0.0,0.0,12.250,0.0,0.0,4.58,1557.0,4410.0,4410.0,943.0,4623.0,456.0,4563.0,256.0,3.5000,0.0,0.0,5.0,2.0,2.0,0.0,37.586,64.002,0.09091,7.0,0.92384,0.0,0.0,0.0
570078,1656.0,0.2726,41.623,0.0,0.0,4955.0,4955.0,4955.0,65010.0,0.0,58125.0,0.0,0.0,74325.0,594600.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.00,1963.0,2190.0,2190.0,61.0,8060.0,4623.0,0.0,839.0,16.6667,0.0,0.0,6.0,13.0,0.0,0.0,0.000,0.000,0.52632,0.0,0.74912,0.0,0.0,1.0
570079,1915.0,0.4451,0.000,0.0,0.0,6918.0,7433.0,6918.0,7433.0,14351.0,0.0,514.0,0.0,4955000.0,0.0,0.0,0.0,0.0,0.0,0.0,6.920,0.0,0.0,6.92,3407.0,3407.0,3407.0,30386.0,3407.0,0.0,0.0,112.0,0.0833,0.0,0.0,1.0,1.0,0.0,0.0,0.000,0.000,0.00000,2.0,1.00000,0.0,0.0,1.0

# Training clean after merging

In [17]:
train_df=pd.read_csv('Training_Missing_removed.csv',index_col='application_key')
colm= [ i for i in range(48)]
train_df.columns=colm
med_colm=[0,1,2,3,4,8,9,18,19,27,28,32,33,35,36,37,38,41,42,43]
zero_replace_colm=[5,6,7,10,11,12,14,15,16,17,20,21,22,23,24,25,26,
                  29,30,31,34,39,40,44,45]
train_df[med_colm]=train_df[med_colm].replace(np.NaN,train_df[med_colm].median())
train_df[zero_replace_colm]=train_df[zero_replace_colm].replace(np.NaN,0)
train_df[[6]]=train_df[[6]].values+train_df[[7]].values
train_df[[15]]=train_df[[16]].values+train_df[[17]].values+train_df[[15]].values
train_df[[21]]=train_df[[21]].values+train_df[[22]].values
train_df[[25]]=train_df[[25]].values+train_df[[26]].values
train_df[[29]]=train_df[[29]].values+train_df[[30]].values
train_df[[39]]=train_df[[39]].values+train_df[[40]].values
train_df[[44]]=train_df[[44]].values+train_df[[45]].values
drop_colm=[7,16,17,22,26,30,40,45]
replace1_colm=[6,15,21,25,29,39,44]
train_df=train_df.drop(drop_colm,axis=1)
train_df[train_df[replace1_colm]>1]=1
# train_df.to_csv('Training_cleaned_merge3oct.csv')
# train_df.shape

(80000, 40)

In [18]:
# train_df.head()

,0,1,2,3,4,5,6,8,9,10,11,12,13,14,15,18,19,20,21,23,24,25,27,28,29,31,32,33,34,35,36,37,38,39,41,42,43,44,46,47
application_key,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
230032,1696.0,1.6541,0.000,0.0,0.0,0.0,1.0,40369.0,18414.0,0.0,6423.0,3067.0,123875.0,0.0,1.0,3.0,3.0,94.78,1.0,72.25,1462.0,1.0,61.0,4532.0,1.0,625.0,1.1667,1.0,0.0,8.0,10.0,4.0,1.0,1.0,0.08696,10.0,0.63899,0.0,0.0,0.0
230033,1846.0,0.8095,0.000,0.0,0.0,102.0,1.0,18234.0,13664.0,0.0,765.0,1931.0,42613.0,0.0,0.0,0.0,0.0,74.25,1.0,4.80,1028.0,1.0,30386.0,2281.0,1.0,169.0,0.4167,0.0,0.0,8.0,0.0,2.0,0.0,1.0,0.00000,13.0,0.63836,0.0,1.0,1.0
230034,1745.0,0.4001,0.000,0.0,0.0,0.0,1.0,14171.0,2536.0,0.0,0.0,0.0,76109.0,0.0,0.0,0.0,0.0,0.00,0.0,0.00,0.0,0.0,669.0,4623.0,1.0,0.0,25.0833,0.0,0.0,1.0,3.0,1.0,0.0,1.0,0.00000,1.0,1.00000,0.0,0.0,1.0
230035,1739.0,0.2193,0.000,0.0,0.0,1982.0,1.0,20316.0,37013.0,0.0,0.0,0.0,84235.0,0.0,0.0,0.0,0.0,0.00,0.0,0.00,1308.0,1.0,91.0,5992.0,1.0,215.0,10.3333,0.0,0.0,3.0,3.0,2.0,0.0,1.0,0.15385,3.0,0.53241,0.0,1.0,0.0
230036,1787.0,0.0118,0.225,0.0,0.0,5451.0,1.0,7987.0,4696.0,0.0,2257.0,27815.0,123875.0,524848.0,0.0,0.0,0.0,20.51,1.0,28.72,801.0,1.0,487.0,2707.0,1.0,158.0,0.9167,0.0,0.0,2.0,3.0,2.0,0.0,1.0,0.00000,1.0,0.92665,0.0,1.0,0.0

# LeadBoard and Evalution Merging clean

In [15]:
train_df=pd.read_csv('Leaderboard_Missing_removed.csv',index_col='application_key')
colm= [ i for i in range(47)]
train_df.columns=colm
med_colm=[0,1,2,3,4,8,9,18,19,27,28,32,33,35,36,37,38,41,42,43]
zero_replace_colm=[5,6,7,10,11,12,14,15,16,17,20,21,22,23,24,25,26,
                  29,30,31,34,39,40,44,45]
train_df[med_colm]=train_df[med_colm].replace(np.NaN,train_df[med_colm].median())
train_df[zero_replace_colm]=train_df[zero_replace_colm].replace(np.NaN,0)
train_df[[6]]=train_df[[6]].values+train_df[[7]].values
train_df[[15]]=train_df[[16]].values+train_df[[17]].values+train_df[[15]].values
train_df[[21]]=train_df[[21]].values+train_df[[22]].values
train_df[[25]]=train_df[[25]].values+train_df[[26]].values
train_df[[29]]=train_df[[29]].values+train_df[[30]].values
train_df[[39]]=train_df[[39]].values+train_df[[40]].values
train_df[[44]]=train_df[[44]].values+train_df[[45]].values
drop_colm=[7,16,17,22,26,30,40,45]
replace1_colm=[6,15,21,25,29,39,44]
train_df=train_df.drop(drop_colm,axis=1)
train_df[train_df[replace1_colm]>1]=1
train_df.to_csv('lead_')

,0,1,2,3,4,5,6,8,9,10,11,12,13,14,15,18,19,20,21,23,24,25,27,28,29,31,32,33,34,35,36,37,38,39,41,42,43,44,46
application_key,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
350053,1753.0,0.5001,0.000,0.0,0.0,206.0,1.0,14221.0,19438.0,0.0,785.0,0.0,27748.0,375830.0,0.0,1.0,1.0,79.200,1.0,79.20,1141.0,1.0,1551.0,8486.0,1.0,450.0,13.0833,0.0,0.0,3.0,11.0,1.0,0.0,1.0,0.42105,3.0,0.85661,0.0,1.0
350054,1894.0,1.9701,0.000,0.0,0.0,297.0,1.0,176895.0,66346.0,0.0,1816.0,944.0,89190.0,0.0,0.0,0.0,0.0,55.200,1.0,2.97,2186.0,1.0,30386.0,10220.0,1.0,1222.0,1.8333,0.0,0.0,3.0,12.0,3.0,0.0,1.0,0.00000,15.0,0.94391,0.0,0.0
350055,1774.0,0.1718,0.000,0.0,0.0,197.0,1.0,8869.0,3637.0,73.0,4079.0,6999.0,79280.0,373607.0,0.0,2.0,2.0,79.154,0.0,79.15,2068.0,1.0,1490.0,5901.0,1.0,340.0,0.9167,0.0,0.0,3.0,4.0,1.0,0.0,1.0,0.33333,3.0,0.76467,0.0,0.0
350056,1586.0,0.1123,5.299,0.0,0.0,0.0,0.0,14072.0,0.0,4537.0,0.0,0.0,69370.0,114062.0,0.0,0.0,0.0,0.000,0.0,0.00,1034.0,1.0,30.0,2281.0,0.0,34.0,0.5833,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.50000,0.0,0.73274,0.0,0.0
350057,1832.0,1.4442,0.000,0.0,0.0,179.0,1.0,21059.0,20306.0,0.0,8740.0,8012.0,99100.0,331985.0,0.0,1.0,1.0,97.989,0.0,97.99,639.0,1.0,30386.0,4502.0,1.0,84.0,2.0000,0.0,0.0,17.0,0.0,3.0,0.0,1.0,0.00000,23.0,0.79190,0.0,1.0